In [2]:
import numpy as np

In [15]:
#single dimension array
lst= [1, 2, 3, 4, 5]

arr = np.array(lst)

In [4]:
print(type(arr))
print(arr.shape)

<class 'numpy.ndarray'>
(10,)


In [12]:
#multi dimension array
list1 = [1,2,3,4,5]
list2 = [5,6,7,8,9]
list3 = [9,10,11,12,13]

arr2 = np.array([list1, list2, list3])
print(type(arr2))
print(arr2.shape)
print(arr2)


<class 'numpy.ndarray'>
(3, 5)
[[ 1  2  3  4  5]
 [ 5  6  7  8  9]
 [ 9 10 11 12 13]]


In [20]:
#need to take data from indexing 
print(arr[2])
arr[2] = 4
print(arr[2])

# if i want to recer the array or need
# data gap like i want data of index 0,2,4

print(arr[::2])
#if want to rever then i just write third params -1
#if want data in rever and jump both then add gap vaue in negative

print(arr[::-2])

5
4
[1 4 5]
[5 4 1]


In [21]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9],
       [ 9, 10, 11, 12, 13]])

In [ ]:
#i want data of 2 row and 3 row but index of 1 and end 2 
'''[6,7]
10,11]'''
arr2[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [25]:
arr2[1:,3:]

array([[ 8,  9],
       [12, 13]])

In [27]:
arr2[0:,3:]

array([[ 4,  5],
       [ 8,  9],
       [12, 13]])

In [32]:
arr2[:,[0,-1]]

array([[ 1,  5],
       [ 5,  9],
       [ 9, 13]])

In [35]:
#if want to chnage the array dimention with (3,5) to (5,3)
arr2.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  5],
       [ 6,  7,  8],
       [ 9,  9, 10],
       [11, 12, 13]])

In [ ]:
#to Re aggenge th data in sequence 

newshape = np.arange(1,9,1).copy()


In [42]:
newshape.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [43]:
newshape + newshape

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [ ]:
#need random value with random .randint

np.random.randint(1,6,(3,4))


array([[2, 3, 4, 4],
       [2, 2, 5, 2],
       [2, 3, 2, 4]], dtype=int32)

In [47]:
#need random value like Standerd deviation -1 to 1 
#then use randn function

np.random.randn(2,4)

array([[-0.92380431,  0.08380858,  1.45401507, -0.55253899],
       [-0.93843115, -0.44344946, -1.70666572, -0.78780293]])

In [ ]:
#It will take data from 0 to 1 and show in array data 
np.random.random_sample((1,4))

array([[0.37892026, 0.02805604, 0.90985921, 0.89479847]])